class Country {
String name;       
char continent;    
byte states;       
short populationMillions; 
int areaSqKm;      
long gdp;         
float literacyRate; 
double hdi;        
boolean isDeveloped; 
public static void main(String[] args) {
Country c0 = new Country();
c0.name = "India"; 
c0.continent = 'A'; 
c0.states = 28; 
c0.populationMillions = 1391; 
c0.areaSqKm = 3287263; 
c0.gdp = 3130000000000L; 
c0.literacyRate = 77.7f; 
c0.hdi = 0.645; 
c0.isDeveloped = false;
System.out.println("Country  Details");
System.out.println("Name: "+c0.name);
System.out.println("Continent: "+c0.continent);
System.out.println("States: "+c0.states);
System.out.println("Population (millions): "+c0.populationMillions);
System.out.println("Area (sq km): "+c0.areaSqKm);
System.out.println("GDP: "+c0.gdp);
System.out.println("Literacy Rate: "+c0.literacyRate+"%");
System.out.println("HDI: "+c0.hdi);
System.out.println("Developed: "+c0.isDeveloped);
System.out.println("===============================");
Country c1 = new Country();
c1.name = "USA"; 
c1.continent='N'; 
c1.states=50; 
c1.populationMillions=331; 
c1.areaSqKm=9833520; 
c1.gdp=21433225000000L; 
c1.literacyRate=99.0f; 
c1.hdi=0.926; 
c1.isDeveloped=true;
System.out.println("Country  Details");
System.out.println("Name: "+c1.name);
System.out.println("Continent: "+c1.continent);
System.out.println("States: "+c1.states);
System.out.println("Population (millions): "+c1.populationMillions);
System.out.println("Area (sq km): "+c1.areaSqKm);
System.out.println("GDP: "+c1.gdp);
System.out.println("Literacy Rate: "+c1.literacyRate+"%");
System.out.println("HDI: "+c1.hdi);
System.out.println("Developed: "+c1.isDeveloped);
System.out.println("===============================");
Country c2 = new Country();
c2.name="Japan"; 
c2.continent='A'; 
c2.states=47; 
c2.populationMillions=126;
c2.areaSqKm=377975; 
c2.gdp=5081770000000L; 
c2.literacyRate=99.0f;
c2.hdi=0.919; 
c2.isDeveloped=true;
System.out.println("Country  Details");
System.out.println("Name: "+c2.name);
System.out.println("Continent: "+c2.continent);
System.out.println("States: "+c2.states);
System.out.println("Population (millions): "+c2.populationMillions);
System.out.println("Area (sq km): "+c2.areaSqKm);
System.out.println("GDP: "+c2.gdp);
System.out.println("Literacy Rate: "+c2.literacyRate+"%");
System.out.println("HDI: "+c2.hdi);
System.out.println("Developed: "+c2.isDeveloped);
System.out.println("===============================");
Country c3 = new Country();
c3.name="Germany"; 
c3.continent='E'; 
c3.states=16; 
c3.populationMillions=83;
c3.areaSqKm=357022; 
c3.gdp=3845630000000L; 
c3.literacyRate=99.0f;
c3.hdi=0.947; 
c3.isDeveloped=true;
System.out.println("Country  Details");
System.out.println("Name: "+c3.name);
System.out.println("Continent: "+c3.continent);
System.out.println("States: "+c3.states);
System.out.println("Population (millions): "+c3.populationMillions);
System.out.println("Area (sq km): "+c3.areaSqKm);
System.out.println("GDP: "+c3.gdp);
System.out.println("Literacy Rate: "+c3.literacyRate+"%");
System.out.println("HDI: "+c3.hdi);
System.out.println("Developed: "+c3.isDeveloped);
System.out.println("===============================");
Country c4 = new Country();
c4.name="Brazil"; 
c4.continent='S'; 
c4.states=26; 
c4.populationMillions=213;
c4.areaSqKm=8515767; 
c4.gdp=1839758000000L; 
c4.literacyRate=93.2f;
c4.hdi=0.765; 
c4.isDeveloped=false;
System.out.println("Country  Details");
System.out.println("Name: "+c4.name);
System.out.println("Continent: "+c4.continent);
System.out.println("States: "+c4.states);
System.out.println("Population (millions): "+c4.populationMillions);
System.out.println("Area (sq km): "+c4.areaSqKm);
System.out.println("GDP: "+c4.gdp);
System.out.println("Literacy Rate: "+c4.literacyRate+"%");
System.out.println("HDI: "+c4.hdi);
System.out.println("Developed: "+c4.isDeveloped);
System.out.println("===============================");
Country c5 = new Country();
c5.name="Canada"; 
c5.continent='N'; 
c5.states=10; 
c5.populationMillions=38;
c5.areaSqKm=9984670; 
c5.gdp=1736420000000L; 
c5.literacyRate=99.0f;
c5.hdi=0.929; 
c5.isDeveloped=true;
System.out.println("Country  Details");
System.out.println("Name: "+c5.name);
System.out.println("Continent: "+c5.continent);
System.out.println("States: "+c5.states);
System.out.println("Population (millions): "+c5.populationMillions);
System.out.println("Area (sq km): "+c5.areaSqKm);
System.out.println("GDP: "+c5.gdp);
System.out.println("Literacy Rate: "+c5.literacyRate+"%");
System.out.println("HDI: "+c5.hdi);
System.out.println("Developed: "+c5.isDeveloped);
System.out.println("===============================");
Country c6 = new Country();
c6.name="Australia"; 
c6.continent='O'; 
c6.states=6; 
c6.populationMillions=25;
c6.areaSqKm=7692024; 
c6.gdp=1392687000000L; 
c6.literacyRate=99.0f;
c6.hdi=0.944; 
c6.isDeveloped=true;
System.out.println("Country  Details");
System.out.println("Name: "+c6.name);
System.out.println("Continent: "+c6.continent);
System.out.println("States: "+c6.states);
System.out.println("Population (millions): "+c6.populationMillions);
System.out.println("Area (sq km): "+c6.areaSqKm);
System.out.println("GDP: "+c6.gdp);
System.out.println("Literacy Rate: "+c6.literacyRate+"%");
System.out.println("HDI: "+c6.hdi);
System.out.println("Developed: "+c6.isDeveloped);
System.out.println("===============================");
Country c7 = new Country();
c7.name="Russia"; 
c7.continent='E'; 
c7.states=85; 
c7.populationMillions=146;
c7.areaSqKm=17098242; 
c7.gdp=1680970000000L; 
c7.literacyRate=99.7f;
c7.hdi=0.824; 
c7.isDeveloped=false;
System.out.println("Country  Details");
System.out.println("Name: "+c7.name);
System.out.println("Continent: "+c7.continent);
System.out.println("States: "+c7.states);
System.out.println("Population (millions): "+c7.populationMillions);
System.out.println("Area (sq km): "+c7.areaSqKm);
System.out.println("GDP: "+c7.gdp);
System.out.println("Literacy Rate: "+c7.literacyRate+"%");
System.out.println("HDI: "+c7.hdi);
System.out.println("Developed: "+c7.isDeveloped);
System.out.println("===============================");
Country c8 = new Country();
c8.name="Egypt"; 
c8.continent='A'; 
c8.states=27; 
c8.populationMillions=102;
c8.areaSqKm=1002450; 
c8.gdp=404000000000L; 
c8.literacyRate=71.2f;
c8.hdi=0.707; 
c8.isDeveloped=false;
System.out.println("Country  Details");
System.out.println("Name: "+c8.name);
System.out.println("Continent: "+c8.continent);
System.out.println("States: "+c8.states);
System.out.println("Population (millions): "+c8.populationMillions);
System.out.println("Area (sq km): "+c8.areaSqKm);
System.out.println("GDP: "+c8.gdp);
System.out.println("Literacy Rate: "+c8.literacyRate+"%");
System.out.println("HDI: "+c8.hdi);
System.out.println("Developed: "+c8.isDeveloped);
System.out.println("===============================");
Country c9 = new Country();
System.out.println("Country  Details ");
System.out.println("Name: "+c9.name);
System.out.println("Continent: "+c9.continent);
System.out.println("States: "+c9.states);
System.out.println("Population (millions): "+c9.populationMillions);
System.out.println("Area (sq km): "+c9.areaSqKm);
System.out.println("GDP: "+c9.gdp);
System.out.println("Literacy Rate: "+c9.literacyRate+"%");
System.out.println("HDI: "+c9.hdi);
System.out.println("Developed: "+c9.isDeveloped);
    }
}
