class Movie {
String title;       
char genre;        
byte awards;        
short duration;    
int releaseYear;  
long boxOffice;   
float rating;       
double budget;     
boolean isSequel;   
public static void main(String[] args) {
Movie m0 = new Movie();
m0.title = "Inception"; 
m0.genre='S'; 
m0.awards=4; 
m0.duration=148; 
m0.releaseYear=2010;
m0.boxOffice=829895144L; 
m0.rating=8.8f; 
m0.budget=160000000; 
m0.isSequel=false;
System.out.println("Movie 0 Details");
System.out.println("Title: "+m0.title);
System.out.println("Genre: "+m0.genre);
System.out.println("Awards: "+m0.awards);
System.out.println("Duration: "+m0.duration+" mins");
System.out.println("Release Year: "+m0.releaseYear);
System.out.println("Box Office: "+m0.boxOffice);
System.out.println("Rating: "+m0.rating);
System.out.println("Budget: "+m0.budget);
System.out.println("Sequel: "+m0.isSequel);
System.out.println("===============================");
Movie m1 = new Movie();
m1.title="Avatar"; 
m1.genre='F'; 
m1.awards=3; 
m1.duration=162; 
m1.releaseYear=2009;
m1.boxOffice=2787965087L; 
m1.rating=7.8f; 
m1.budget=237000000; 
m1.isSequel=true;
System.out.println("Movie 1 Details");
System.out.println("Title: "+m1.title);
System.out.println("Genre: "+m1.genre);
System.out.println("Awards: "+m1.awards);
System.out.println("Duration: "+m1.duration+" mins");
System.out.println("Release Year: "+m1.releaseYear);
System.out.println("Box Office: "+m1.boxOffice);
System.out.println("Rating: "+m1.rating);
System.out.println("Budget: "+m1.budget);
System.out.println("Sequel: "+m1.isSequel);
System.out.println("===============================");
Movie m2 = new Movie();
m2.title="Titanic"; 
m2.genre='R'; 
m2.awards=11; 
m2.duration=195; 
m2.releaseYear=1997;
m2.boxOffice=2187463944L; 
m2.rating=7.9f; 
m2.budget=200000000; 
m2.isSequel=false;
System.out.println("Movie 2 Details");
System.out.println("Title: "+m2.title);
System.out.println("Genre: "+m2.genre);
System.out.println("Awards: "+m2.awards);
System.out.println("Duration: "+m2.duration+" mins");
System.out.println("Release Year: "+m2.releaseYear);
System.out.println("Box Office: "+m2.boxOffice);
System.out.println("Rating: "+m2.rating);
System.out.println("Budget: "+m2.budget);
System.out.println("Sequel: "+m2.isSequel);
System.out.println("===============================");
Movie m3 = new Movie();
m3.title="Avengers"; 
m3.genre='A'; 
m3.awards=5; 
m3.duration=143; 
m3.releaseYear=2012;
m3.boxOffice=1518812988L; 
m3.rating=8.1f; 
m3.budget=220000000; 
m3.isSequel=true;
System.out.println("Movie 3 Details");
System.out.println("Title: "+m3.title);
System.out.println("Genre: "+m3.genre);
System.out.println("Awards: "+m3.awards);
System.out.println("Duration: "+m3.duration+" mins");
System.out.println("Release Year: "+m3.releaseYear);
System.out.println("Box Office: "+m3.boxOffice);
System.out.println("Rating: "+m3.rating);
System.out.println("Budget: "+m3.budget);
System.out.println("Sequel: "+m3.isSequel);
System.out.println("===============================");
Movie m4 = new Movie();
m4.title="Joker"; 
m4.genre='D'; 
m4.awards=2; 
m4.duration=122; 
m4.releaseYear=2019;
m4.boxOffice=1074251311L;
m4.rating=8.5f; 
m4.budget=55000000; 
m4.isSequel=false;
System.out.println("Movie 4 Details");
System.out.println("Title: "+m4.title);
System.out.println("Genre: "+m4.genre);
System.out.println("Awards: "+m4.awards);
System.out.println("Duration: "+m4.duration+" mins");
System.out.println("Release Year: "+m4.releaseYear);
System.out.println("Box Office: "+m4.boxOffice);
System.out.println("Rating: "+m4.rating);
System.out.println("Budget: "+m4.budget);
System.out.println("Sequel: "+m4.isSequel);
System.out.println("===============================");
Movie m5 = new Movie();
m5.title="Interstellar"; 
m5.genre='S'; 
m5.awards=6; 
m5.duration=169; 
m5.releaseYear=2014;
m5.boxOffice=677471339L; 
m5.rating=8.6f; 
m5.budget=165000000; 
m5.isSequel=false;
System.out.println("Movie 5 Details");
System.out.println("Title: "+m5.title);
System.out.println("Genre: "+m5.genre);
System.out.println("Awards: "+m5.awards);
System.out.println("Duration: "+m5.duration+" mins");
System.out.println("Release Year: "+m5.releaseYear);
System.out.println("Box Office: "+m5.boxOffice);
System.out.println("Rating: "+m5.rating);
System.out.println("Budget: "+m5.budget);
System.out.println("Sequel: "+m5.isSequel);
System.out.println("===============================");
Movie m6 = new Movie();
m6.title="Frozen"; 
m6.genre='A'; 
m6.awards=2; 
m6.duration=102; 
m6.releaseYear=2013;
m6.boxOffice=1276480335L; 
m6.rating=7.5f; 
m6.budget=150000000; 
m6.isSequel=true;
System.out.println("Movie 6 Details");
System.out.println("Title: "+m6.title);
System.out.println("Genre: "+m6.genre);
System.out.println("Awards: "+m6.awards);
System.out.println("Duration: "+m6.duration+" mins");
System.out.println("Release Year: "+m6.releaseYear);
System.out.println("Box Office: "+m6.boxOffice);
System.out.println("Rating: "+m6.rating);
System.out.println("Budget: "+m6.budget);
System.out.println("Sequel: "+m6.isSequel);
System.out.println("===============================");
Movie m7 = new Movie();
m7.title="Gladiator"; 
m7.genre='A'; 
m7.awards=5; 
m7.duration=155; 
m7.releaseYear=2000;
m7.boxOffice=460583960L; 
m7.rating=8.5f; 
m7.budget=103000000; 
m7.isSequel=false;
System.out.println("Movie 7 Details");
System.out.println("Title: "+m7.title);
System.out.println("Genre: "+m7.genre);
System.out.println("Awards: "+m7.awards);
System.out.println("Duration: "+m7.duration+" mins");
System.out.println("Release Year: "+m7.releaseYear);
System.out.println("Box Office: "+m7.boxOffice);
System.out.println("Rating: "+m7.rating);
System.out.println("Budget: "+m7.budget);
System.out.println("Sequel: "+m7.isSequel);
System.out.println("===============================");
Movie m8 = new Movie();
m8.title="The Godfather"; 
m8.genre='D'; 
m8.awards=3; 
m8.duration=175; 
m8.releaseYear=1972;
m8.boxOffice=246120974L; 
m8.rating=9.2f; 
m8.budget=6000000; 
m8.isSequel=true;
System.out.println("Movie 8 Details");
System.out.println("Title: "+m8.title);
System.out.println("Genre: "+m8.genre);
System.out.println("Awards: "+m8.awards);
System.out.println("Duration: "+m8.duration+" mins");
System.out.println("Release Year: "+m8.releaseYear);
System.out.println("Box Office: "+m8.boxOffice);
System.out.println("Rating: "+m8.rating);
System.out.println("Budget: "+m8.budget);
System.out.println("Sequel: "+m8.isSequel);
System.out.println("===============================");
Movie m9 = new Movie();
System.out.println("Movie 9 Details");
System.out.println("Title: "+m9.title);
System.out.println("Genre: "+m9.genre);
System.out.println("Awards: "+m9.awards);
System.out.println("Duration: "+m9.duration+" mins");
System.out.println("Release Year: "+m9.releaseYear);
System.out.println("Box Office: "+m9.boxOffice);
System.out.println("Rating: "+m9.rating);
System.out.println("Budget: "+m9.budget);
System.out.println("Sequel: "+m9.isSequel);
    }
}
