class Restaurant {
String name;       
short tables;       
int revenue;       
long totalRevenue;  
float rating;       
double averageBill; 
char type;         
boolean isOpen;     
byte awards;        
public static void main(String[] args) {
Restaurant r0 = new Restaurant();
r0.name = "Olive Garden"; 
r0.tables = 25; 
r0.revenue = 1500; 
r0.totalRevenue = 1500000L;
r0.rating = 4.5f; 
r0.averageBill = 30.5; 
r0.type = 'F'; 
r0.isOpen = true; 
r0.awards = 5;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r0.name);
System.out.println("Tables: " + r0.tables);
System.out.println("Revenue (in thousands): " + r0.revenue);
System.out.println("Total Revenue: " + r0.totalRevenue);
System.out.println("Rating: " + r0.rating);
System.out.println("Average Bill: " + r0.averageBill);
System.out.println("Type: " + r0.type);
System.out.println("Open: " + r0.isOpen);
System.out.println("Awards: " + r0.awards);
System.out.println("===============================");
Restaurant r1 = new Restaurant();
r1.name = "Pizza Hut"; 
r1.tables = 20; 
r1.revenue = 1200; 
r1.totalRevenue = 1200000L;
r1.rating = 4.2f; 
r1.averageBill = 25.0; 
r1.type = 'Q'; 
r1.isOpen = true; 
r1.awards = 3;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r1.name);
System.out.println("Tables: " + r1.tables);
System.out.println("Revenue (in thousands): " + r1.revenue);
System.out.println("Total Revenue: " + r1.totalRevenue);
System.out.println("Rating: " + r1.rating);
System.out.println("Average Bill: " + r1.averageBill);
System.out.println("Type: " + r1.type);
System.out.println("Open: " + r1.isOpen);
System.out.println("Awards: " + r1.awards);
System.out.println("===============================");
Restaurant r2 = new Restaurant();
r2.name = "Starbucks"; 
r2.tables = 15; 
r2.revenue = 900; 
r2.totalRevenue = 900000L;
r2.rating = 4.6f; 
r2.averageBill = 12.5; 
r2.type = 'Q'; 
r2.isOpen = false; 
r2.awards = 2;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r2.name);
System.out.println("Tables: " + r2.tables);
System.out.println("Revenue (in thousands): " + r2.revenue);
System.out.println("Total Revenue: " + r2.totalRevenue);
System.out.println("Rating: " + r2.rating);
System.out.println("Average Bill: " + r2.averageBill);
System.out.println("Type: " + r2.type);
System.out.println("Open: " + r2.isOpen);
System.out.println("Awards: " + r2.awards);
System.out.println("===============================");
Restaurant r3 = new Restaurant();
r3.name = "McDonald's"; 
r3.tables = 30; 
r3.revenue = 2000; 
r3.totalRevenue = 2000000L;
r3.rating = 4.0f;
r3.averageBill = 15.0; 
r3.type = 'Q'; 
r3.isOpen = true; 
r3.awards = 4;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r3.name);
System.out.println("Tables: " + r3.tables);
System.out.println("Revenue (in thousands): " + r3.revenue);
System.out.println("Total Revenue: " + r3.totalRevenue);
System.out.println("Rating: " + r3.rating);
System.out.println("Average Bill: " + r3.averageBill);
System.out.println("Type: " + r3.type);
System.out.println("Open: " + r3.isOpen);
System.out.println("Awards: " + r3.awards);
System.out.println("===============================");
Restaurant r4 = new Restaurant();
r4.name = "Burger King";
r4.tables = 18; 
r4.revenue = 1100; 
r4.totalRevenue = 1100000L;
r4.rating = 3.9f; 
r4.averageBill = 14.0; 
r4.type = 'Q'; 
r4.isOpen = false; 
r4.awards = 2;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r4.name);
System.out.println("Tables: " + r4.tables);
System.out.println("Revenue (in thousands): " + r4.revenue);
System.out.println("Total Revenue: " + r4.totalRevenue);
System.out.println("Rating: " + r4.rating);
System.out.println("Average Bill: " + r4.averageBill);
System.out.println("Type: " + r4.type);
System.out.println("Open: " + r4.isOpen);
System.out.println("Awards: " + r4.awards);
System.out.println("===============================");
Restaurant r5 = new Restaurant();
r5.name = "Nando's"; 
r5.tables = 22; 
r5.revenue = 1300; 
r5.totalRevenue = 1300000L;
r5.rating = 4.3f; 
r5.averageBill = 20.0; 
r5.type = 'F'; 
r5.isOpen = true; 
r5.awards = 3;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r5.name);
System.out.println("Tables: " + r5.tables);
System.out.println("Revenue (in thousands): " + r5.revenue);
System.out.println("Total Revenue: " + r5.totalRevenue);
System.out.println("Rating: " + r5.rating);
System.out.println("Average Bill: " + r5.averageBill);
System.out.println("Type: " + r5.type);
System.out.println("Open: " + r5.isOpen);
System.out.println("Awards: " + r5.awards);
System.out.println("===============================");
Restaurant r6 = new Restaurant();
r6.name = "KFC"; 
r6.tables = 28; 
r6.revenue = 1800; 
r6.totalRevenue = 1800000L;
r6.rating = 4.1f; 
r6.averageBill = 16.0; 
r6.type = 'Q'; 
r6.isOpen = true; 
r6.awards = 4;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r6.name);
System.out.println("Tables: " + r6.tables);
System.out.println("Revenue (in thousands): " + r6.revenue);
System.out.println("Total Revenue: " + r6.totalRevenue);
System.out.println("Rating: " + r6.rating);
System.out.println("Average Bill: " + r6.averageBill);
System.out.println("Type: " + r6.type);
System.out.println("Open: " + r6.isOpen);
System.out.println("Awards: " + r6.awards);
System.out.println("===============================");
Restaurant r7 = new Restaurant();
r7.name = "Domino's"; 
r7.tables = 16; 
r7.revenue = 1000; 
r7.totalRevenue = 1000000L;
r7.rating = 4.0f; 
r7.averageBill = 18.0; 
r7.type = 'Q'; 
r7.isOpen = false; 
r7.awards = 2;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r7.name);
System.out.println("Tables: " + r7.tables);
System.out.println("Revenue (in thousands): " + r7.revenue);
System.out.println("Total Revenue: " + r7.totalRevenue);
System.out.println("Rating: " + r7.rating);
System.out.println("Average Bill: " + r7.averageBill);
System.out.println("Type: " + r7.type);
System.out.println("Open: " + r7.isOpen);
System.out.println("Awards: " + r7.awards);
System.out.println("===============================");
Restaurant r8 = new Restaurant();
r8.name = "Cheesecake Factory";
r8.tables = 24; 
r8.revenue = 1600; 
r8.totalRevenue = 1600000L;
r8.rating = 4.4f; 
r8.averageBill = 35.0; 
r8.type = 'F'; 
r8.isOpen = true; 
r8.awards = 5;
System.out.println("Restaurant  Details");
System.out.println("Name: " + r8.name);
System.out.println("Tables: " + r8.tables);
System.out.println("Revenue (in thousands): " + r8.revenue);
System.out.println("Total Revenue: " + r8.totalRevenue);
System.out.println("Rating: " + r8.rating);
System.out.println("Average Bill: " + r8.averageBill);
System.out.println("Type: " + r8.type);
System.out.println("Open: " + r8.isOpen);
System.out.println("Awards: " + r8.awards);
System.out.println("===============================");
Restaurant r9 = new Restaurant();
System.out.println("Restaurant  Details ");
System.out.println("Name: " + r9.name);
System.out.println("Tables: " + r9.tables);
System.out.println("Revenue (in thousands): " + r9.revenue);
System.out.println("Total Revenue: " + r9.totalRevenue);
System.out.println("Rating: " + r9.rating);
System.out.println("Average Bill: " + r9.averageBill);
System.out.println("Type: " + r9.type);
System.out.println("Open: " + r9.isOpen);
System.out.println("Awards: " + r9.awards);
    }
}
