class Run{
public static void main(String[] args){
Football fb = new Football();
Game.start();
Game.play();
fb.pause();
fb.end();
System.out.println("---------------------------");
Dog dog= new Dog(); 
Animals.eat();
Animals.sleep();
dog.sound();
dog.move();
System.out.println("---------------------------");
Circle circle = new Circle();
Shape.area();
Shape.perimeter();
circle.draw();
circle.describe();
System.out.println("---------------------------");
WashingMachines wm=new WashingMachines();
Machine.start();
Machine.stop();
wm.clean();
wm.rinse();
System.out.println("---------------------------");
Laptops laptop = new Laptops();
Computer.powerOn();
Computer.powerOff();
laptop.runProgram();
laptop.reboot();
System.out.println("---------------------------");
Parrot parrot = new Parrot();
Bird.fly();
Bird.eat();
parrot.sing();
parrot.sleep();
System.out.println("---------------------------");
Refigerator refigerator = new Refigerator();
Appliance.plugIn();
Appliance.cool();
refigerator.defrost();
refigerator.unplug();
System.out.println("---------------------------");
MathTeacher mt = new MathTeacher();
Teacher.prepareLesson();
Teacher.teach();
mt.grade();
mt.attendMeeting();
System.out.println("---------------------------");
Guitar guitar=new Guitar();
Instrument.tune();
Instrument.play();
guitar.clean();
guitar.store();
System.out.println("---------------------------");
Hammer hammer=new Hammer();
Tool.pickUp();
Tool.use();
hammer.clean();
hammer.store();
System.out.println("---------------------------");
CreditAccount ca=new CreditAccount();
Account.open();
Account.deposit();
ca.withdraw();
ca.close();
System.out.println("---------------------------");
Juice juice=new Juice();
Drinks.pour();
Drinks.addIce();
juice.mix();
juice.serve();
System.out.println("---------------------------");
MotorBike trans=new MotorBike();
Transport.start();
Transport.stop();
trans.accelerate();
trans.brake();
System.out.println("---------------------------");
kabaddiPlayer kp=new kabaddiPlayer();
Sports.train();
Sports.playMatch();
kp.rest();
kp.travel();
System.out.println("---------------------------");
Earth earth=new Earth();
Planet.revolve();
Planet.rotate();
earth.atmosphere();
earth.gravity();
System.out.println("---------------------------");
ChickenBiryani cb=new ChickenBiryani();
Food.cook();
Food.eat();
cb.store();
cb.serve();
System.out.println("---------------------------");
Bookcase bci=new Bookcase();
Furniture.assemble();
Furniture.move();
bci.clean();
bci.repair();
System.out.println("---------------------------");
Tablet tablet=new Tablet();
Electronics.switchOn();
Electronics.switchOff();
tablet.charge();
tablet.reset();
System.out.println("---------------------------");
Cat cat=new Cat();
AnimalCare.feed();
AnimalCare.groom();
cat.vaccinate();
cat.exercise();
System.out.println("---------------------------");
Nurse hs=new Nurse();
HospitalStaff.checkPatients();
HospitalStaff.giveMedicine();
hs.maintainRecords();
hs.attendEmergency();
System.out.println("---------------------------");
CPU cp=new CPU();
ComputerParts.install();
ComputerParts.test();
cp.replace();
cp.upgrade();
System.out.println("---------------------------");
Shirt s=new Shirt();
Clothing.design();
Clothing.stitch();
s.wash();
s.iron();
System.out.println("---------------------------");
RoseGarden rosegarden=new RoseGarden();
Garden.plant();
Garden.water();
rosegarden.prune();
rosegarden.harvest();
System.out.println("---------------------------");
CleaningRobot cr=new CleaningRobot();
Robot.start();
Robot.move();
cr.lift();
cr.stop();
System.out.println("---------------------------");
Kitchen k=new Kitchen();
Kitchen.prepareIngredients();
Kitchen.cook();
k.serve();
k.clean();
System.out.println("============");
RestaurantKitchen rk=new RestaurantKitchen();
rk.serve();
rk.clean();
}
}
