class Run{
public static void main(String[] args){
Game gam=new Game();
Game.start();
Game.play();
gam.pause();
gam.end();
Football football=new Football();
football.pause();
football.end();
System.out.println("---------------UPCASTING----------------");
Game g = new Football();
g.score();
g.achievements();
g.foul();
System.out.println("=================Upcasting==================");
Game game=g;
game.score();
game.achievements();
game.foul();
System.out.println("---------------------------");
Animals animal=new Animals();
Animals.eat();
Animals.sleep();
animal.sound();
animal.move();
Dog dg=new Dog();
dg.sound();
dg.move();
System.out.println("---------------UPCASTING----------------");
Animals anim= new Dog(); 
anim.drink();
anim.dig();
anim.grow();
System.out.println("=================Upcasting==================");
Animals as=anim;
as.drink();
as.dig();
as.grow();
System.out.println("---------------------------");
Shape sp=new Shape();
Shape.area();
Shape.perimeter();
sp.draw();
sp.describe();
Circle circle = new Circle();
circle.draw();
circle.describe();
System.out.println("---------------UPCASTING----------------");
Shape shape=new Circle();
shape.resize();
shape.save();
shape.copy();
System.out.println("=================Upcasting==================");
Shape shp=shape;
shp.save();
shp.resize();
shp.copy();
System.out.println("---------------------------");
Machine mc=new Machine();
Machine.start();
Machine.stop();
mc.start();
mc.stop();
WashingMachines wm=new WashingMachines();
wm.clean();
wm.rinse();
System.out.println("---------------UPCASTING----------------");
Machine machine=new WashingMachines();
machine.fillWater();
machine.rotate();
machine.detergent();
System.out.println("=================Upcasting==================");
Machine machi=machine;
machi.rotate();
machi.fillWater();
machi.detergent();
System.out.println("---------------------------");
School sch=new School();
School.startClass();
School.giveHomework();
sch.conductExam();
sch.declareResult();
Pupil  pupil  = new Pupil ();
pupil.conductExam();
pupil.declareResult();
System.out.println("---------------UPCASTING----------------");
School sc=new Pupil();
sc.canteen();
sc.conductSports();
sc.conductLab();
System.out.println("=================Upcasting==================");
School schol=sc;
schol.conductSports();
schol.canteen();
schol.conductLab();
System.out.println("---------------------------");
Bird bd=new Bird();
Bird.fly();
Bird.eat();
bd.sing();
bd.sleep();
Parrot parrot = new Parrot();
parrot.sing();
parrot.sleep();
System.out.println("---------------UPCASTING----------------");
Bird bird=new Parrot();
bird.hunt();
bird.buildNest();
bird.layEggs();
System.out.println("=================Upcasting==================");
Bird bid=bird;
bid.hunt();
bid.buildNest();
bid.layEggs();
System.out.println("---------------------------");
Appliance app=new Appliance();
app.plugIn();
app.cool();
app.defrost();
app.unplug();
Refigerator refigerator = new Refigerator();
refigerator.defrost();
refigerator.unplug();
System.out.println("---------------UPCASTING----------------");
Appliance appl=new Refigerator();
appl.storeFood();
appl.alarm();
appl.temperatureCheck();
System.out.println("=================Upcasting==================");
Appliance appliablce=appl;
appliablce.storeFood();
appliablce.alarm();
appliablce.temperatureCheck();
System.out.println("---------------------------");
Teacher tc=new Teacher();
Teacher.prepareLesson();
Teacher.teach();
tc.grade();
tc.attendMeeting();
MathTeacher mt = new MathTeacher();
mt.grade();
mt.attendMeeting();
System.out.println("---------------UPCASTING----------------");
Teacher tr=new MathTeacher();
tr.planExam();
tr.attendance();
tr.records();
System.out.println("=================Upcasting==================");
Teacher tcher=tr;
tcher.planExam();
tcher.attendance();
tcher.records();
System.out.println("---------------------------");
Instrument ins=new Instrument();
Instrument.tune();
Instrument.play();
ins.clean();
ins.store();
Guitar guitar=new Guitar();
guitar.clean();
guitar.store();
System.out.println("---------------UPCASTING----------------");
Instrument instr=new Guitar();
instr.testSound();
instr.decorate();
instr.adjustStrings();
System.out.println("=================Upcasting==================");
Instrument instrument=instr;
instrument.testSound();
instrument.decorate();
instrument.adjustStrings();
System.out.println("---------------------------");
Tool tl=new Tool();
Tool.pickUp();
Tool.use();
tl.clean();
tl.store();
Hammer hammer=new Hammer();
hammer.clean();
hammer.store();
System.out.println("---------------UPCASTING----------------");
Tool to=new Hammer();
to.repair();
to.label();
to.test();
System.out.println("=================Upcasting==================");
Tool tool=to;
tool.label();
tool.repair();
tool.test();
System.out.println("---------------------------");
Account acco=new Account();
Account.open();
Account.deposit();
acco.withdraw();
acco.close();
CreditAccount ca=new CreditAccount();
ca.withdraw();
ca.close();
System.out.println("---------------UPCASTING----------------");
Account at=new CreditAccount();
at.applyLoan();
at.updateDetails();
at.interest();
System.out.println("=================Upcasting==================");
Account account=at;
account.applyLoan();
account.updateDetails();
account.interest();
System.out.println("---------------------------");
Drinks ds=new Drinks();
Drinks.pour();
Drinks.addIce();
ds.mix();
ds.serve();
Juice juice=new Juice();
juice.mix();
juice.serve();
System.out.println("---------------UPCASTING----------------");
Drinks dins=new Juice();
dins.label();
dins.taste();
dins.close();
System.out.println("=================Upcasting==================");
Drinks drinks=dins;
drinks.label();
drinks.taste();
drinks.close();
System.out.println("---------------------------");
Transport tp=new Transport();
Transport.start();
Transport.stop();
tp.accelerate();
tp.brake();
MotorBike trans=new MotorBike();
trans.accelerate();
trans.brake();
System.out.println("---------------UPCASTING----------------");
Transport tsp=new MotorBike();
tsp.refuel();
tsp.park();
tsp.turnLeft();
System.out.println("=================Upcasting==================");
Transport transport=tsp;
transport.refuel();
transport.turnLeft();
transport.park();
System.out.println("---------------------------");
Sports ss=new Sports();
Sports.train();
Sports.playMatch();
ss.rest();
ss.travel();
kabaddiPlayer kp=new kabaddiPlayer();
kp.rest();
kp.travel();
System.out.println("---------------UPCASTING----------------");
Sports spor=new kabaddiPlayer();
spor.warmUp();
spor.meetCoach();
spor.practice();
System.out.println("=================Upcasting==================");
Sports sport=spor;
sport.warmUp();
sport.meetCoach();
sport.practice();
System.out.println("---------------------------");
Planet ptt=new Planet();
Planet.revolve();
Planet.rotate();
ptt.atmosphere();
ptt.gravity();
  ptt.temperature();
Earth earth=new Earth();
earth.atmosphere();
earth.gravity();
  earth.temperature();
System.out.println("---------------UPCASTING----------------");
Planet palnt=new Earth();
palnt.gravity();
palnt.orbit();
palnt.magneticField();
System.out.println("=================Upcasting==================");
Planet planet=palnt;
planet.gravity();
planet.orbit();
planet.magneticField();
System.out.println("---------------------------");
Food fo=new Food();
Food.cook();
Food.eat();
fo.store();
fo.serve();
ChickenBiryani cb=new ChickenBiryani();
cb.store();
cb.serve();
System.out.println("---------------UPCASTING----------------");
Food food=new ChickenBiryani();
food.order();
food.taste();
food.deliver();
System.out.println("=================Upcasting==================");
Food food1=food;
food1.taste();
food1.order();
food1.deliver();
System.out.println("---------------------------");
Furniture fur=new Furniture();
Furniture.assemble();
Furniture.move();
fur.clean();
fur.repair();
Bookcase bci=new Bookcase();
bci.clean();
bci.repair();
System.out.println("---------------UPCASTING----------------");
Furniture fu=new Bookcase();
fu.decorate();
fu.store();
fu.paint();
System.out.println("=================Upcasting==================");
Furniture furnit=fu;
furnit.decorate();
furnit.store();
furnit.paint();
System.out.println("---------------------------");
Electronics elc=new Electronics();
Electronics.switchOn();
Electronics.switchOff();
elc.charge();
elc.reset();
Tablet tablet=new Tablet();
tablet.charge();
tablet.reset();
System.out.println("---------------UPCASTING----------------");
Electronics electronics=new Tablet();
electronics.displayInfo();
electronics.adjustBrightness();
electronics.playMusic();
System.out.println("=================Upcasting==================");
Electronics electroni=electronics;
electroni.displayInfo();
electroni.adjustBrightness();
electroni.playMusic();
System.out.println("---------------------------");
AnimalCare acare=new AnimalCare();
AnimalCare.feed();
AnimalCare.groom();
acare.vaccinate();
acare.exercise();
Cat cat=new Cat();
cat.vaccinate();
cat.exercise();
System.out.println("---------------UPCASTING----------------");
AnimalCare animalcare=new Cat();
animalcare.play();
animalcare.train();
animalcare.dietPlan();
System.out.println("=================Upcasting==================");
AnimalCare animm=animalcare;
animm.play();
animm.dietPlan();
animm.train();
System.out.println("---------------------------");
HospitalStaff hstaff=new HospitalStaff();
HospitalStaff.checkPatients();
HospitalStaff.giveMedicine();
hstaff.maintainRecords();
hstaff.attendEmergency();
Nurse hs=new Nurse();
hs.maintainRecords();
hs.attendEmergency();
System.out.println("---------------UPCASTING----------------");
HospitalStaff hosp=new Nurse();
hosp.updateReport();
hosp.appointment();
hosp.patientComfort();
System.out.println("=================Upcasting==================");
HospitalStaff hospstaff=hosp;
hospstaff.appointment();
hospstaff.updateReport();
hospstaff.patientComfort();
System.out.println("---------------------------");
ComputerParts computer=new ComputerParts();
ComputerParts.install();
ComputerParts.test();
computer.replace();
computer.upgrade();
CPU cp=new CPU();
cp.replace();
cp.upgrade();
System.out.println("---------------UPCASTING----------------");
ComputerParts cparts=new CPU();
cparts.troubleshoot();
cparts.secure();
cparts.activiy();
System.out.println("=================Upcasting==================");
ComputerParts compparts=cparts;
compparts.secure();
compparts.troubleshoot();
compparts.activiy();
System.out.println("---------------------------");
Clothing cg=new Clothing();
Clothing.design();
Clothing.stitch();
cg.wash();
cg.iron();
Shirt s=new Shirt();
s.wash();
s.iron();
System.out.println("---------------UPCASTING----------------");
Clothing cloth=new Shirt();
cloth.sell();
cloth.pack();
cloth.dye();
System.out.println("=================Upcasting==================");
Clothing clothing=cloth;
clothing.sell();
clothing.pack();
clothing.dye();
System.out.println("---------------------------");
Garden garrd=new Garden();
Garden.plant();
Garden.water();
garrd.prune();
garrd.harvest();
RoseGarden rosegarden=new RoseGarden();
rosegarden.prune();
rosegarden.harvest();
System.out.println("---------------UPCASTING----------------");
Garden garden=new RoseGarden();
garden.plantSeeds();
garden.decorate();
garden.grow();
System.out.println("=================Upcasting==================");
Garden gards=garden;
gards.plantSeeds();
gards.decorate();
gards.grow();
System.out.println("---------------------------");
Robot rb=new Robot();
Robot.start();
Robot.move();
rb.lift();
rb.stop();
System.out.println("============");
CleaningRobot cr=new CleaningRobot();
cr.lift();
cr.stop();
System.out.println("---------------UPCASTING----------------");
Robot rbot=new CleaningRobot();
rbot.scan();
rbot.repair();
rbot.charge();
System.out.println("=================Upcasting==================");
Robot rbott=rbot;
rbott.scan();
rbott.repair();
rbott.charge();
System.out.println("---------------------------");
Kitchen k=new Kitchen();
Kitchen.prepareIngredients();
Kitchen.cook();
k.serve();
k.clean();
System.out.println("============");
RestaurantKitchen rk=new RestaurantKitchen();
rk.serve();
rk.clean();
System.out.println("---------------UPCASTING----------------");
Kitchen kit=new RestaurantKitchen();
kit.takeOrders();
kit.billing();
kit.washDishes();
System.out.println("=================Upcasting==================");
Kitchen kitc=kit;
kitc.takeOrders();
kitc.billing();
kitc.washDishes();
}
}
