class Smartphone {
String brand;      
char os;           
byte cameras;      
short ramGB;       
int storageGB;     
long price;        
float screenSize;  
double battery;    
boolean is5G;      
public static void main(String[] args) {
Smartphone s0 = new Smartphone();
s0.brand="Apple"; 
s0.os='i'; 
s0.cameras=3; 
s0.ramGB=6; 
s0.storageGB=128;
s0.price=120000L; 
s0.screenSize=6.1f; 
s0.battery=3110.0; 
s0.is5G=true;
System.out.println("Smartphone 0 Details");
System.out.println("Brand: "+s0.brand);
System.out.println("OS: "+s0.os);
System.out.println("Cameras: "+s0.cameras);
System.out.println("RAM: "+s0.ramGB+" GB");
System.out.println("Storage: "+s0.storageGB+" GB");
System.out.println("Price: "+s0.price);
System.out.println("Screen Size: "+s0.screenSize+" inch");
System.out.println("Battery: "+s0.battery+" mAh");
System.out.println("5G Support: "+s0.is5G);
System.out.println("===============================");
Smartphone s1 = new Smartphone();
s1.brand="Samsung"; 
s1.os='A'; 
s1.cameras=4; 
s1.ramGB=8; 
s1.storageGB=256;
s1.price=90000L; 
s1.screenSize=6.5f; 
s1.battery=4500.0; 
s1.is5G=true;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s1.brand);
System.out.println("OS: "+s1.os);
System.out.println("Cameras: "+s1.cameras);
System.out.println("RAM: "+s1.ramGB+" GB");
System.out.println("Storage: "+s1.storageGB+" GB");
System.out.println("Price: "+s1.price);
System.out.println("Screen Size: "+s1.screenSize+" inch");
System.out.println("Battery: "+s1.battery+" mAh");
System.out.println("5G Support: "+s1.is5G);
System.out.println("===============================");
Smartphone s2 = new Smartphone();
s2.brand="OnePlus"; 
s2.os='A'; 
s2.cameras=3; 
s2.ramGB=12; 
s2.storageGB=256;
s2.price=55000L; 
s2.screenSize=6.7f; 
s2.battery=4500.0; 
s2.is5G=true;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s2.brand);
System.out.println("OS: "+s2.os);
System.out.println("Cameras: "+s2.cameras);
System.out.println("RAM: "+s2.ramGB+" GB");
System.out.println("Storage: "+s2.storageGB+" GB");
System.out.println("Price: "+s2.price);
System.out.println("Screen Size: "+s2.screenSize+" inch");
System.out.println("Battery: "+s2.battery+" mAh");
System.out.println("5G Support: "+s2.is5G);
System.out.println("===============================");
Smartphone s3 = new Smartphone();
s3.brand="Xiaomi"; 
s3.os='A'; 
s3.cameras=5; 
s3.ramGB=8; 
s3.storageGB=128;
s3.price=35000L; 
s3.screenSize=6.4f; 
s3.battery=5020.0; 
s3.is5G=true;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s3.brand);
System.out.println("OS: "+s3.os);
System.out.println("Cameras: "+s3.cameras);
System.out.println("RAM: "+s3.ramGB+" GB");
System.out.println("Storage: "+s3.storageGB+" GB");
System.out.println("Price: "+s3.price);
System.out.println("Screen Size: "+s3.screenSize+" inch");
System.out.println("Battery: "+s3.battery+" mAh");
System.out.println("5G Support: "+s3.is5G);
Smartphone s4 = new Smartphone();
s4.brand="Google"; 
s4.os='A'; 
s4.cameras=2; 
s4.ramGB=6; 
s4.storageGB=128;
s4.price=60000L; 
s4.screenSize=6.3f; 
s4.battery=4080.0; 
s4.is5G=true;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s4.brand);
System.out.println("OS: "+s4.os);
System.out.println("Cameras: "+s4.cameras);
System.out.println("RAM: "+s4.ramGB+" GB");
System.out.println("Storage: "+s4.storageGB+" GB");
System.out.println("Price: "+s4.price);
System.out.println("Screen Size: "+s4.screenSize+" inch");
System.out.println("Battery: "+s4.battery+" mAh");
System.out.println("5G Support: "+s4.is5G);
System.out.println("===============================");
Smartphone s5 = new Smartphone();
s5.brand="Oppo"; 
s5.os='A'; 
s5.cameras=4; 
s5.ramGB=8; 
s5.storageGB=128;
s5.price=30000L; 
s5.screenSize=6.4f; 
s5.battery=4310.0; 
s5.is5G=true;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s5.brand);
System.out.println("OS: "+s5.os);
System.out.println("Cameras: "+s5.cameras);
System.out.println("RAM: "+s5.ramGB+" GB");
System.out.println("Storage: "+s5.storageGB+" GB");
System.out.println("Price: "+s5.price);
System.out.println("Screen Size: "+s5.screenSize+" inch");
System.out.println("Battery: "+s5.battery+" mAh");
System.out.println("5G Support: "+s5.is5G);
System.out.println("===============================");
Smartphone s6 = new Smartphone();
s6.brand="Vivo"; 
s6.os='A'; 
s6.cameras=3; 
s6.ramGB=6; 
s6.storageGB=64;
s6.price=20000L; 
s6.screenSize=6.5f; 
s6.battery=4100.0; 
s6.is5G=false;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s6.brand);
System.out.println("OS: "+s6.os);
System.out.println("Cameras: "+s6.cameras);
System.out.println("RAM: "+s6.ramGB+" GB");
System.out.println("Storage: "+s6.storageGB+" GB");
System.out.println("Price: "+s6.price);
System.out.println("Screen Size: "+s6.screenSize+" inch");
System.out.println("Battery: "+s6.battery+" mAh");
System.out.println("5G Support: "+s6.is5G);
System.out.println("===============================");
Smartphone s7 = new Smartphone();
s7.brand="Realme"; 
s7.os='A'; 
s7.cameras=4; 
s7.ramGB=8; 
s7.storageGB=128;
s7.price=25000L; 
s7.screenSize=6.6f; 
s7.battery=4300.0; 
s7.is5G=true;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s7.brand);
System.out.println("OS: "+s7.os);
System.out.println("Cameras: "+s7.cameras);
System.out.println("RAM: "+s7.ramGB+" GB");
System.out.println("Storage: "+s7.storageGB+" GB");
System.out.println("Price: "+s7.price);
System.out.println("Screen Size: "+s7.screenSize+" inch");
System.out.println("Battery: "+s7.battery+" mAh");
System.out.println("5G Support: "+s7.is5G);
System.out.println("===============================");
Smartphone s8 = new Smartphone();
s8.brand="Motorola"; 
s8.os='A'; 
s8.cameras=2; 
s8.ramGB=4; 
s8.storageGB=64;
s8.price=15000L; 
s8.screenSize=6.2f; 
s8.battery=4000.0; 
s8.is5G=false;
System.out.println("Smartphone  Details");
System.out.println("Brand: "+s8.brand);
System.out.println("OS: "+s8.os);
System.out.println("Cameras: "+s8.cameras);
System.out.println("RAM: "+s8.ramGB+" GB");
System.out.println("Storage: "+s8.storageGB+" GB");
System.out.println("Price: "+s8.price);
System.out.println("Screen Size: "+s8.screenSize+" inch");
System.out.println("Battery: "+s8.battery+" mAh");
System.out.println("5G Support: "+s8.is5G);
System.out.println("===============================");
Smartphone s9 = new Smartphone();
System.out.println("Smartphone  Details ");
System.out.println("Brand: "+s9.brand);
System.out.println("OS: "+s9.os);
System.out.println("Cameras: "+s9.cameras);
System.out.println("RAM: "+s9.ramGB+" GB");
System.out.println("Storage: "+s9.storageGB+" GB");
System.out.println("Price: "+s9.price);
System.out.println("Screen Size: "+s9.screenSize+" inch");
System.out.println("Battery: "+s9.battery+" mAh");
System.out.println("5G Support: "+s9.is5G);
    }
}
