class Vehicle {
byte wheels;
short speed;
int price;
long registrationNo;
float mileage;
double enginePower;
char fuelType;
boolean isElectric;
String brand;
public static void main(String[] args) {
Vehicle v=new Vehicle();
v.wheels=4;
v.speed=100;
v.price=500000;
v.registrationNo=1237435457849l;
v.mileage=18.5f;
v.enginePower=150.0;
v.fuelType='P';
v.isElectric=true;
v.brand="Honda";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v.wheels);
System.out.println("The vehicle speed is : "+v.speed);
System.out.println("Vehicle price : "+v.price);
System.out.println("registered Vehicle Number : "+v.registrationNo);
System.out.println("The Vehicle mile is : "+v.mileage);
System.out.println("Their engine : "+v.enginePower);
System.out.println("Fueltype is : "+v.fuelType);
System.out.println("Is the Vehicle is Electric : "+v.isElectric);
System.out.println("Vehicle Brand is : "+v.brand);
System.out.println("===============================");
Vehicle v1=new Vehicle();
v1.wheels = 2;
v1.speed = 120;
v1.price = 120000;
v1.registrationNo = 9876543210123L;
v1.mileage = 45.0f;
v1.enginePower = 80.0;
v1.fuelType = 'P';
v1.isElectric = false;
v1.brand = "TVS";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v1.wheels);
System.out.println("The vehicle speed is : "+v1.speed);
System.out.println("Vehicle price : "+v1.price);
System.out.println("registered Vehicle Number : "+v1.registrationNo);
System.out.println("The Vehicle mile is : "+v1.mileage);
System.out.println("Their engine : "+v1.enginePower);
System.out.println("Fueltype is : "+v1.fuelType);
System.out.println("Is the Vehicle is Electric : "+v1.isElectric);
System.out.println("Vehicle Brand is : "+v1.brand);
System.out.println("===============================");
Vehicle v2=new Vehicle();
v2.wheels = 4;
v2.speed = 90;
v2.price = 350000;
v2.registrationNo = 1122334455667L;
v2.mileage = 20.0f;
v2.enginePower = 140.0;
v2.fuelType = 'D';
v2.isElectric = false;
v2.brand = "Ford";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v2.wheels);
System.out.println("The vehicle speed is : "+v2.speed);
System.out.println("Vehicle price : "+v2.price);
System.out.println("registered Vehicle Number : "+v2.registrationNo);
System.out.println("The Vehicle mile is : "+v2.mileage);
System.out.println("Their engine : "+v2.enginePower);
System.out.println("Fueltype is : "+v2.fuelType);
System.out.println("Is the Vehicle is Electric : "+v2.isElectric);
System.out.println("Vehicle Brand is : "+v2.brand);
System.out.println("===============================");
Vehicle v3=new Vehicle();
v3.wheels = 4;
v3.speed = 110;
v3.price = 600000;
v3.registrationNo = 9988776655443L;
v3.mileage = 16.0f;
v3.enginePower = 160.0;
v3.fuelType = 'P';
v3.isElectric = true;
v3.brand = "Tesla";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v3.wheels);
System.out.println("The vehicle speed is : "+v3.speed);
System.out.println("Vehicle price : "+v3.price);
System.out.println("registered Vehicle Number : "+v3.registrationNo);
System.out.println("The Vehicle mile is : "+v3.mileage);
System.out.println("Their engine : "+v3.enginePower);
System.out.println("Fueltype is : "+v3.fuelType);
System.out.println("Is the Vehicle is Electric : "+v3.isElectric);
System.out.println("Vehicle Brand is : "+v3.brand);
System.out.println("===============================");
Vehicle v4=new Vehicle();
v4.wheels = 4;
v4.speed = 95;
v4.price = 450000;
v4.registrationNo = 2233445566778L;
v4.mileage = 19.0f;
v4.enginePower = 130.0;
v4.fuelType = 'D';
v4.isElectric = false;
v4.brand = "Hyundai";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v4.wheels);
System.out.println("The vehicle speed is : "+v4.speed);
System.out.println("Vehicle price : "+v4.price);
System.out.println("registered Vehicle Number : "+v4.registrationNo);
System.out.println("The Vehicle mile is : "+v4.mileage);
System.out.println("Their engine : "+v4.enginePower);
System.out.println("Fueltype is : "+v4.fuelType);
System.out.println("Is the Vehicle is Electric : "+v4.isElectric);
System.out.println("Vehicle Brand is : "+v4.brand);
System.out.println("===============================");
Vehicle v5=new Vehicle();
v5.wheels = 2;
v5.speed = 85;
v5.price = 90000;
v5.registrationNo = 5566778899001L;
v5.mileage = 50.0f;
v5.enginePower = 75.0;
v5.fuelType = 'P';
v5.isElectric = true;
v5.brand = "Hero";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v5.wheels);
System.out.println("The vehicle speed is : "+v5.speed);
System.out.println("Vehicle price : "+v5.price);
System.out.println("registered Vehicle Number : "+v5.registrationNo);
System.out.println("The Vehicle mile is : "+v5.mileage);
System.out.println("Their engine : "+v5.enginePower);
System.out.println("Fueltype is : "+v5.fuelType);
System.out.println("Is the Vehicle is Electric : "+v5.isElectric);
System.out.println("Vehicle Brand is : "+v5.brand);
System.out.println("===============================");
Vehicle v6=new Vehicle();
v6.wheels = 4;
v6.speed = 130;
v6.price = 700000;
v6.registrationNo = 6677889900112L;
v6.mileage = 15.0f;
v6.enginePower = 170.0;
v6.fuelType = 'P';
v6.isElectric = true;
v6.brand = "BMW";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v6.wheels);
System.out.println("The vehicle speed is : "+v6.speed);
System.out.println("Vehicle price : "+v6.price);
System.out.println("registered Vehicle Number : "+v6.registrationNo);
System.out.println("The Vehicle mile is : "+v6.mileage);
System.out.println("Their engine : "+v6.enginePower);
System.out.println("Fueltype is : "+v6.fuelType);
System.out.println("Is the Vehicle is Electric : "+v6.isElectric);
System.out.println("Vehicle Brand is : "+v6.brand);
System.out.println("===============================");
Vehicle v7=new Vehicle();
v7.wheels = 4;
v7.speed = 105;
v7.price = 480000;
v7.registrationNo = 7788990011223L;
v7.mileage = 17.5f;
v7.enginePower = 145.0;
v7.fuelType = 'D';
v7.isElectric = false;
v7.brand = "Mahindra";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v7.wheels);
System.out.println("The vehicle speed is : "+v7.speed);
System.out.println("Vehicle price : "+v7.price);
System.out.println("registered Vehicle Number : "+v7.registrationNo);
System.out.println("The Vehicle mile is : "+v7.mileage);
System.out.println("Their engine : "+v7.enginePower);
System.out.println("Fueltype is : "+v7.fuelType);
System.out.println("Is the Vehicle is Electric : "+v7.isElectric);
System.out.println("Vehicle Brand is : "+v7.brand);
System.out.println("===============================");
Vehicle v8=new Vehicle();
v8.wheels = 2;
v8.speed = 110;
v8.price = 150000;
v8.registrationNo = 8899001122334L;
v8.mileage = 42.0f;
v8.enginePower = 85.0;
v8.fuelType = 'P';
v8.isElectric = true;
v8.brand = "Yamaha";
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v8.wheels);
System.out.println("The vehicle speed is : "+v8.speed);
System.out.println("Vehicle price : "+v8.price);
System.out.println("registered Vehicle Number : "+v8.registrationNo);
System.out.println("The Vehicle mile is : "+v8.mileage);
System.out.println("Their engine : "+v8.enginePower);
System.out.println("Fueltype is : "+v8.fuelType);
System.out.println("Is the Vehicle is Electric : "+v8.isElectric);
System.out.println("Vehicle Brand is : "+v8.brand);
System.out.println("===============================");
Vehicle v9=new Vehicle();
System.out.println("Vehicle Details");
System.out.println("Havin wheels: "+v9.wheels);
System.out.println("The vehicle speed is : "+v9.speed);
System.out.println("Vehicle price : "+v9.price);
System.out.println("registered Vehicle Number : "+v9.registrationNo);
System.out.println("The Vehicle mile is : "+v9.mileage);
System.out.println("Their engine : "+v9.enginePower);
System.out.println("Fueltype is : "+v9.fuelType);
System.out.println("Is the Vehicle is Electric : "+v9.isElectric);
System.out.println("Vehicle Brand is : "+v9.brand);
}
}